# syntax=docker/dockerfile:1.2
FROM python:3.8-slim

WORKDIR /usr/src/app

ENV PYTHONPATH=. \
  VENV=/opt/venv

RUN python3 -m venv $VENV
ENV PATH="$VENV/bin:$PATH"

COPY ./requirements.txt ./
RUN pip install -r requirements.txt

ENV FLASK_ENV=development
CMD ["flask", "run", "--host=0.0.0.0", "--no-reload"]
